services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000" # adapte ce port à celui utilisé dans ton Express.js
    restart: unless-stopped
    environment:
      NODE_ENV: production
